/*
 * Copyright (c) 2025-2026 Datalayer, Inc.
 * Distributed under the terms of the Modified BSD License.
 */

/**
 * Team Specifications.
 *
 * THIS FILE IS AUTO-GENERATED from YAML team specifications.
 * DO NOT EDIT MANUALLY - run 'make specs' to regenerate.
 */

import type { TeamSpec } from '../../types';

// ============================================================================
// Team Definitions
// ============================================================================

export const ANALYZE_CAMPAIGN_PERFORMANCE_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'analyze-campaign-performance',
  version: '0.0.1',
  name: 'Analyze Campaign Performance Team',
  description: `A multi-agent team that unifies marketing data from Google Ads, Meta, TikTok, LinkedIn, GA4, CRM, and email platforms. Normalises metrics into a unified view, detects performance anomalies in real time, and generates budget reallocation recommendations to maximise ROAS.`,
  tags: [
    'marketing',
    'media',
    'campaigns',
    'analytics',
    'advertising',
    'social-media',
  ],
  enabled: true,
  icon: 'megaphone',
  emoji: '📢',
  color: '#8250df',
  agentSpecId: 'analyze-campaign-performance:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Campaign Analytics Orchestrator Agent',
    ref: '',
    model: 'openai-gpt-4-1',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Start with Platform Connector to pull data from all ad platforms, then Metrics Normaliser for unified KPIs, then Anomaly Detector for real-time performance monitoring, then Budget Optimiser for reallocation recommendations. Escalate CPA spikes above 50% immediately.`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'cp-1',
      name: 'Platform Connector Agent',
      ref: '',
      role: 'initiator',
      goal: `Pull campaign data from Google Ads, Meta, TikTok, LinkedIn, GA4, and email platforms`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Ad Platforms MCP',
      tools: [
        'Google Ads Connector',
        'Meta Ads Connector',
        'TikTok Ads Connector',
        'LinkedIn Ads Connector',
        'GA4 Connector',
      ],
      trigger: 'Schedule: Every 4 hours',
      approval: 'auto',
    },
    {
      id: 'cp-2',
      name: 'Metrics Normaliser Agent',
      ref: '',
      role: 'contributor',
      goal: `Normalise CPA, ROAS, CTR, and attribution across all platforms into unified view`,
      dependsOn: ['cp-1'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Analytics MCP',
      tools: [
        'Metric Unifier',
        'Currency Converter',
        'Attribution Mapper',
        'Naming Convention Resolver',
      ],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'cp-3',
      name: 'Anomaly Detector Agent',
      ref: '',
      role: 'contributor',
      goal: `Monitor all KPIs for CTR drops, CPA spikes, and budget pacing issues`,
      dependsOn: ['cp-2'],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Monitoring MCP',
      tools: [
        'Anomaly Scanner',
        'Budget Pacer',
        'Alert Generator',
        'Campaign Pauser',
      ],
      trigger: '',
      approval: 'manual',
    },
    {
      id: 'cp-4',
      name: 'Budget Optimiser Agent',
      ref: '',
      role: 'finalizer',
      goal: `Generate budget reallocation recommendations to maximise ROAS across channels`,
      dependsOn: ['cp-3'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Optimisation MCP',
      tools: [
        'ROAS Calculator',
        'Budget Allocator',
        'Scenario Modeller',
        'Report Generator',
      ],
      trigger: '',
      approval: 'manual',
    },
  ],
  reactionRules: [
    {
      id: 'rr-camp-1',
      trigger: 'budget_threshold_exceeded',
      action: 'pause_and_notify',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'high',
    },
    {
      id: 'rr-camp-2',
      trigger: 'data_quality_low',
      action: 'retry_collection',
      auto: true,
      maxRetries: 3,
      escalateAfterRetries: 3,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'csv', 'json'],
    template: 'Campaign Performance Report',
    storage: 's3://reports/campaign-analytics/',
  },
};

export const ANALYZE_SUPPORT_TICKETS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'analyze-support-tickets',
  version: '0.0.1',
  name: 'Analyze Support Tickets Team',
  description: `A multi-agent team that triages incoming support tickets, categorizes by urgency and topic, identifies recurring patterns, and generates resolution recommendations with escalation paths.`,
  tags: ['analytics', 'data', 'support', 'tickets'],
  enabled: true,
  icon: 'issue-opened',
  emoji: '🎫',
  color: '#bf8700',
  agentSpecId: 'analyze-support-tickets:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Support Orchestrator Agent',
    ref: '',
    model: 'openai-gpt-4-1',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Route new tickets to the Triage Agent first, then to the Categorizer, then to the Pattern Analyzer. Escalate P1/critical tickets immediately to human support leads.`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '180s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'st-1',
      name: 'Triage Agent',
      ref: '',
      role: 'initiator',
      goal: `Ingest new support tickets and assess urgency level (P1-P4)`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Helpdesk MCP',
      tools: ['Ticket Reader', 'Priority Classifier'],
      trigger: 'Event: new ticket received',
      approval: 'auto',
    },
    {
      id: 'st-2',
      name: 'Categorizer Agent',
      ref: '',
      role: 'contributor',
      goal: `Categorize tickets by topic, product area, and sentiment`,
      dependsOn: ['st-1'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'NLP Pipeline MCP',
      tools: ['Topic Classifier', 'Sentiment Analyzer', 'Product Tagger'],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'st-3',
      name: 'Pattern Analyzer Agent',
      ref: '',
      role: 'finalizer',
      goal: `Identify recurring issues and generate resolution recommendations`,
      dependsOn: ['st-2'],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Analytics MCP',
      tools: [
        'Pattern Detector',
        'Knowledge Base Search',
        'Resolution Generator',
      ],
      trigger: '',
      approval: 'manual',
    },
  ],
  reactionRules: [
    {
      id: 'rr-supp-1',
      trigger: 'ticket_surge_detected',
      action: 'escalate_to_supervisor',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'high',
    },
    {
      id: 'rr-supp-2',
      trigger: 'classification_confidence_low',
      action: 'request_human_review',
      auto: false,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '15s',
    staleThreshold: '60s',
    unresponsiveThreshold: '180s',
    stuckThreshold: '300s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: false,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'json'],
    template: 'Support Ticket Analysis',
    storage: 's3://reports/support-analytics/',
  },
};

export const AUDIT_INVENTORY_LEVELS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'audit-inventory-levels',
  version: '0.0.1',
  name: 'Audit Inventory Levels Team',
  description: `A multi-agent team that monitors inventory levels across warehouses, detects discrepancies between physical and system counts, forecasts demand by SKU, and generates automated reorder recommendations.`,
  tags: ['finance', 'automation', 'inventory', 'supply-chain'],
  enabled: true,
  icon: 'package',
  emoji: '📦',
  color: '#0969da',
  agentSpecId: 'audit-inventory-levels:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Inventory Orchestrator Agent',
    ref: '',
    model: 'openai-gpt-4-1',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Start with the Scanner to pull current levels, then Auditor to check discrepancies, then Forecaster for demand predictions, then Planner for reorder recommendations, then Reporter for the final audit report. Escalate critical shortages immediately.`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '600s', retryOnFailure: true, maxRetries: 3 },
  agents: [
    {
      id: 'inv-1',
      name: 'Inventory Scanner Agent',
      ref: '',
      role: 'initiator',
      goal: `Pull current inventory levels from all warehouse management systems`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Warehouse MCP',
      tools: ['WMS Connector', 'Barcode Scanner API'],
      trigger: 'Schedule: Every 6 hours',
      approval: 'auto',
    },
    {
      id: 'inv-2',
      name: 'Discrepancy Auditor Agent',
      ref: '',
      role: 'contributor',
      goal: `Compare system counts vs physical counts and flag discrepancies`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Audit MCP',
      tools: ['Count Comparator', 'Discrepancy Logger', 'Shrinkage Calculator'],
      trigger: 'On completion of Inventory Scanner',
      approval: 'auto',
    },
    {
      id: 'inv-3',
      name: 'Demand Forecaster Agent',
      ref: '',
      role: 'contributor',
      goal: `Forecast demand by SKU using historical sales and seasonal patterns`,
      dependsOn: [],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Analytics MCP',
      tools: [
        'Time Series Model',
        'Seasonal Analyzer',
        'External Signals Fetcher',
      ],
      trigger: 'On completion of Discrepancy Auditor',
      approval: 'auto',
    },
    {
      id: 'inv-4',
      name: 'Reorder Planner Agent',
      ref: '',
      role: 'contributor',
      goal: `Calculate optimal reorder points and generate purchase order recommendations`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Procurement MCP',
      tools: ['EOQ Calculator', 'Supplier Catalog', 'PO Generator'],
      trigger: 'On completion of Demand Forecaster',
      approval: 'manual',
    },
    {
      id: 'inv-5',
      name: 'Audit Report Agent',
      ref: '',
      role: 'finalizer',
      goal: `Compile inventory audit report with discrepancies, forecasts, and reorder plan`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Document Generation MCP',
      tools: ['PDF Generator', 'Chart Builder', 'Email Sender'],
      trigger: 'On completion of Reorder Planner',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-inv-1',
      trigger: 'stockout_risk_detected',
      action: 'escalate_to_supervisor',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'high',
    },
    {
      id: 'rr-inv-2',
      trigger: 'discrepancy_threshold_exceeded',
      action: 'flag_for_manual_audit',
      auto: false,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'high',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'xlsx', 'csv'],
    template: 'Inventory Audit Report',
    storage: 's3://reports/inventory-audits/',
  },
};

export const AUTOMATE_REGULATORY_REPORTING_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'automate-regulatory-reporting',
  version: '0.0.1',
  name: 'Automate Regulatory Reporting Team',
  description: `A multi-agent team that automates end-to-end regulatory reporting for financial institutions. Ingests data from trading systems, risk engines, and accounting platforms, reconciles positions, computes risk metrics, validates against regulatory rules (Basel III/IV, MiFID II, SOX), and generates submission-ready compliance reports with full audit trails.`,
  tags: ['finance', 'compliance', 'regulatory', 'risk', 'banking', 'audit'],
  enabled: true,
  icon: 'shield-check',
  emoji: '🏦',
  color: '#0969da',
  agentSpecId: 'automate-regulatory-reporting:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Compliance Orchestrator Agent',
    ref: '',
    model: 'openai-gpt-4-1',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Start with Data Ingestion to pull positions and transactions, then Risk Calculator for metric computation, then Reconciliation Agent to cross-check figures, then Validation Agent for regulatory rule checks, then Report Generator for submission-ready output. Escalate any reconciliation breaks above $10K immediately to the compliance team.`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '900s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'reg-1',
      name: 'Data Ingestion Agent',
      ref: '',
      role: 'initiator',
      goal: `Extract positions, transactions, and P&L from trading and accounting systems`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Trading Systems MCP',
      tools: ['Position Reader', 'Transaction Fetcher', 'P&L Extractor'],
      trigger: 'Schedule: Monthly on the 3rd business day',
      approval: 'auto',
    },
    {
      id: 'reg-2',
      name: 'Risk Calculator Agent',
      ref: '',
      role: 'contributor',
      goal: `Compute Basel III/IV risk-weighted assets, capital ratios, and VaR metrics`,
      dependsOn: ['reg-1'],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Risk Engine MCP',
      tools: [
        'RWA Calculator',
        'VaR Engine',
        'Capital Ratio Computer',
        'Stress Test Runner',
      ],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'reg-3',
      name: 'Reconciliation Agent',
      ref: '',
      role: 'contributor',
      goal: `Cross-check computed figures against source systems and flag discrepancies`,
      dependsOn: ['reg-2'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Reconciliation MCP',
      tools: ['Position Reconciler', 'Break Detector', 'Audit Logger'],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'reg-4',
      name: 'Validation Agent',
      ref: '',
      role: 'contributor',
      goal: `Validate all metrics against Basel III/IV, MiFID II, and SOX regulatory rules`,
      dependsOn: ['reg-3'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Compliance Rules MCP',
      tools: [
        'Basel Rule Validator',
        'MiFID II Checker',
        'SOX Control Verifier',
      ],
      trigger: '',
      approval: 'manual',
    },
    {
      id: 'reg-5',
      name: 'Report Generator Agent',
      ref: '',
      role: 'finalizer',
      goal: `Generate submission-ready regulatory reports with full data lineage and audit trail`,
      dependsOn: ['reg-4'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Document Generation MCP',
      tools: ['PDF Generator', 'XBRL Formatter', 'Email Sender'],
      trigger: '',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-reg-1',
      trigger: 'compliance_violation_detected',
      action: 'halt_and_escalate',
      auto: true,
      maxRetries: 0,
      escalateAfterRetries: 0,
      priority: 'critical',
    },
    {
      id: 'rr-reg-2',
      trigger: 'data_validation_failure',
      action: 'retry_with_fallback',
      auto: true,
      maxRetries: 3,
      escalateAfterRetries: 3,
      priority: 'high',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '15s',
    staleThreshold: '60s',
    unresponsiveThreshold: '120s',
    stuckThreshold: '300s',
    maxRestartAttempts: 2,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'xbrl', 'json'],
    template: 'Regulatory Submission Report',
    storage: 's3://reports/regulatory-submissions/',
  },
};

export const COMPREHENSIVE_SALES_ANALYTICS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'comprehensive-sales-analytics',
  version: '0.0.1',
  name: 'Comprehensive Sales Analytics Team',
  description: `A multi-agent team that replaces a single KPI monitor with four specialized agents: a Data Collector that pulls real-time CRM metrics, an Anomaly Detector that flags statistical outliers, a Trend Analyzer that identifies patterns and forecasts, and a Report Generator that compiles executive dashboards and sends alerts. Together they deliver deeper insights, faster detection, and richer reporting than any single agent could.`,
  tags: ['sales', 'analytics', 'kpi', 'monitoring', 'horizontal'],
  enabled: true,
  icon: 'graph',
  emoji: '📈',
  color: '#1a7f37',
  agentSpecId: 'comprehensive-sales-analytics:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Sales Analytics Supervisor',
    ref: '',
    model: 'bedrock:us.anthropic.claude-sonnet-4-6',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Route data collection to KPI Collector first, then pass raw metrics to Anomaly Detector and Trend Analyzer in parallel, then aggregate all outputs into the Report Generator. Escalate if anomalies exceed the critical threshold (>25% deviation from target).`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 3 },
  agents: [
    {
      id: 'sa-1',
      name: 'KPI Data Collector',
      ref: '',
      role: 'initiator',
      goal: `Pull real-time sales metrics from CRM, ERP, and marketing platforms. Normalize data into a unified schema with timestamps, dimensions (region, product line, rep), and measures (revenue, pipeline, conversion).`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'CRM Data Server',
      tools: ['get_sales_data', 'get_customer_list', 'API Connector'],
      trigger: 'Schedule: Daily at 7:30 AM',
      approval: 'auto',
    },
    {
      id: 'sa-2',
      name: 'Anomaly Detector',
      ref: '',
      role: 'contributor',
      goal: `Apply statistical anomaly detection (Z-score, IQR, moving average) to the collected KPIs. Flag any metric deviating more than 10% from its rolling 30-day average. Classify anomalies as info, warning, or critical.`,
      dependsOn: ['sa-1'],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Analytics Server',
      tools: ['run_analysis', 'Statistical Analysis', 'ML Predictor'],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'sa-3',
      name: 'Trend Analyzer',
      ref: '',
      role: 'contributor',
      goal: `Identify week-over-week, month-over-month, and quarter-over-quarter trends. Generate 30-day forecasts for each KPI using time-series models. Highlight the top 3 improving and top 3 declining metrics.`,
      dependsOn: ['sa-1'],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Analytics Server',
      tools: ['run_analysis', 'generate_charts', 'Forecaster'],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'sa-4',
      name: 'Executive Report Generator',
      ref: '',
      role: 'finalizer',
      goal: `Compile all insights — raw KPIs, anomalies, trends, and forecasts — into a polished executive dashboard with charts, tables, and narrative commentary. Send the report via Slack and email. Highlight critical anomalies with a red-flag summary at the top.`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Document Generation MCP',
      tools: [
        'PDF Generator',
        'Chart Builder',
        'Email Sender',
        'Slack Notifier',
      ],
      trigger: 'On completion of Anomaly Detector & Trend Analyzer',
      approval: 'manual',
    },
  ],
  reactionRules: [
    {
      id: 'rr-sales-1',
      trigger: 'anomaly_critical',
      action: 'escalate_to_supervisor',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'high',
    },
    {
      id: 'rr-sales-2',
      trigger: 'data_stale',
      action: 'retry_collection',
      auto: true,
      maxRetries: 3,
      escalateAfterRetries: 3,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'xlsx', 'json'],
    template: 'Executive Sales Dashboard',
    storage: 's3://reports/sales-analytics/',
  },
};

export const JUPYTER_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'jupyter',
  version: '0.0.1',
  name: 'Jupyter Team',
  description: `Six agents working in the same Jupyter notebook: the Analyst adds and runs the cells, the Reviewer checks them and records what it finds, the Writer writes the result up between them, Decks turns what they found into a presentation, the Tutor teaches the person Python in the cells they have, and the Compactor rewrites the notebook as short as it can be without changing what it computes.`,
  tags: [
    'notebook',
    'jupyter',
    'collaboration',
    'analysis',
    'review',
    'presentations',
    'teaching',
    'refactoring',
  ],
  enabled: true,
  icon: 'book',
  emoji: '📓',
  color: '#F37726',
  agentSpecId: '',
  orchestrationProtocol: 'datalayer',
  executionMode: 'supervisor',
  supervisor: {
    name: 'Jupyter Analyst',
    ref: 'jupyter-data-analyst:0.0.1',
    model: 'bedrock:us.anthropic.claude-sonnet-4-6',
    goal: `Keep the work in the notebook. Answer analysis requests directly; send a request to check something to the Reviewer, a request to write something up to the Writer, a request for slides to Decks, a question about the code to the Tutor and a request to tidy the notebook to the Compactor — and never leave results anywhere but the cells, or the deck made from them.`,
    instructions: ``,
    approval: 'auto',
    canTerminate: false,
  },
  routingInstructions: `Send anything about exploring, computing, plotting or extending the analysis — "analyze", "plot", "compute", "add a cell that…" — to the Jupyter Analyst. Send anything about checking, verifying, doubting or re-running — "find what is wrong", "check this", "is this right", "re-run" — to Jupyter Reviewer. Send anything about explaining, summarising, writing up or verifying the wording of a conclusion to Jupyter Writer. Send anything about slides, a deck or a presentation — "make a deck of this", "turn the findings into slides", "present this", "add a slide" — to Jupyter Decks, which builds the deck from what the cells show and opens it beside the conversation. Send anything about understanding or learning — "what does this do", "why did this fail", "teach me", a request for an exercise — to Jupyter Tutor. Send anything about the shape of the notebook — shortening it, merging cells, removing dead code or stale outputs — to Jupyter Compactor. When a request is two of these, the one that produces cells goes first and the one that reads them follows: the Analyst before the Writer or Decks ("analyze this and write it up", "analyze this and make a deck"), the Tutor before the Compactor ("clean this up and explain what you did"). Never let the Compactor rewrite a notebook the person is still learning from without saying what changed. When none fits, answer directly rather than forcing the request onto a specialist.`,
  suggestions: [
    { text: 'Analyze the dataset', icon: 'graph', emoji: '🔎' },
    { text: 'Find what is wrong', icon: 'checklist', emoji: '🧐' },
    { text: 'Verify the conclusion', icon: 'pencil', emoji: '✍️' },
    { text: 'Turn the findings into a deck', icon: 'project', emoji: '📊' },
    {
      text: 'Explain this notebook cell by cell, as if I am new to Python',
      icon: 'book',
      emoji: '📖',
    },
    {
      text: 'Shorten this notebook without changing what it computes',
      icon: 'fold',
      emoji: '✂️',
    },
  ],
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 1 },
  agents: [
    {
      id: 'analyst',
      name: 'Jupyter Analyst',
      ref: 'jupyter-data-analyst:0.0.1',
      role: 'initiator',
      goal: `Explore the data in the open notebook — add the cells, run them, and leave the results on them for the others to build on.`,
      dependsOn: [],
      subagents: [],
      model: '',
      mcpServer: '',
      tools: [],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'reviewer',
      name: 'Jupyter Reviewer',
      ref: 'jupyter-notebook-reviewer:0.0.1',
      role: 'reviewer',
      goal: `Re-run what matters, find what is wrong or unsupported, and record the verdict in the notebook beside the code it concerns.`,
      dependsOn: [],
      subagents: [],
      model: '',
      mcpServer: '',
      tools: [],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'writer',
      name: 'Jupyter Writer',
      ref: 'jupyter-notebook-writer:0.0.1',
      role: 'finalizer',
      goal: `Write the analysis up between the cells — summary, explanations, conclusion — saying only what the cells support.`,
      dependsOn: [],
      subagents: [],
      model: '',
      mcpServer: '',
      tools: [],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'decks',
      name: 'Jupyter Decks',
      ref: 'worker-decks:0.0.1',
      role: 'contributor',
      goal: `Turn what the notebook found into a deck — a title, the numbers as metrics or a chart, the conclusion — open it beside the conversation, and step through it on request.`,
      dependsOn: [],
      subagents: [],
      model: '',
      mcpServer: '',
      tools: [],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'tutor',
      name: 'Jupyter Tutor',
      ref: 'jupyter-tutor:0.0.1',
      role: 'contributor',
      goal: `Teach the person Python in the notebook they have open — what their code does, why it broke, and what to try next — leaving them able to write the next cell themselves.`,
      dependsOn: [],
      subagents: [],
      model: '',
      mcpServer: '',
      tools: [],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'compactor',
      name: 'Jupyter Compactor',
      ref: 'jupyter-notebook-compactor:0.0.1',
      role: 'finalizer',
      goal: `Rewrite the notebook as short as it can be without changing what it computes, and report exactly which cells were touched.`,
      dependsOn: [],
      subagents: [
        {
          name: 'CellFixer',
          ref: 'jupyter-cell-fixer:0.0.1',
          description: `Fixes a failing cell and proves the fix by running it. Reach for this when compaction uncovers a cell that was already broken — repairing it is not part of compacting, and silently leaving it is worse.`,
          instructions: ``,
        },
        {
          name: 'NotebookReproducer',
          ref: 'jupyter-notebook-reproducer:0.0.1',
          description: `Runs the notebook top to bottom on a fresh sandbox and reports what does not reproduce. Reach for this to prove a compaction changed nothing, which is the claim a compaction rests on.`,
          instructions: ``,
        },
      ],
      model: '',
      mcpServer: '',
      tools: [],
      trigger: '',
      approval: 'manual',
    },
  ],
  reactionRules: [
    {
      id: 'rr-nb-1',
      trigger: 'compaction_would_change_results',
      action: 'request_human_review',
      auto: false,
      maxRetries: 0,
      escalateAfterRetries: 0,
      priority: 'high',
    },
    {
      id: 'rr-nb-2',
      trigger: 'learner_repeatedly_stuck',
      action: 'escalate_to_supervisor',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'medium',
    },
    {
      id: 'rr-nb-3',
      trigger: 'review_found_unsupported_claim',
      action: 'escalate_to_supervisor',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '15s',
    staleThreshold: '60s',
    unresponsiveThreshold: '180s',
    stuckThreshold: '300s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: false,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['ipynb', 'markdown'],
    template: 'Notebook Session Summary',
    storage: '',
  },
};

export const OPTIMIZE_GRID_OPERATIONS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'optimize-grid-operations',
  version: '0.0.1',
  name: 'Optimize Grid Operations Team',
  description: `A multi-agent team that processes millions of IoT sensor data points from smart meters, substations, and renewable generation assets. Predicts equipment failures 2–4 weeks in advance, optimises load balancing across the grid, and reduces unplanned downtime by 50%.`,
  tags: [
    'energy',
    'utilities',
    'smart-grid',
    'iot',
    'predictive-maintenance',
    'sustainability',
  ],
  enabled: true,
  icon: 'zap',
  emoji: '⚡',
  color: '#1a7f37',
  agentSpecId: 'optimize-grid-operations:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Grid Operations Orchestrator Agent',
    ref: '',
    model: 'openai-gpt-4-1',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Start with Sensor Ingestion to process real-time telemetry, then Anomaly Detector for pattern identification, then Failure Predictor for maintenance forecasting, then Grid Balancer for load optimisation. Escalate critical failure predictions (< 48h) immediately to operations dispatch.`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '600s', retryOnFailure: true, maxRetries: 3 },
  agents: [
    {
      id: 'grid-1',
      name: 'Sensor Ingestion Agent',
      ref: '',
      role: 'initiator',
      goal: `Ingest and process real-time telemetry from SCADA, smart meters, and IoT gateways`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'SCADA MCP',
      tools: [
        'SCADA Connector',
        'Smart Meter Reader',
        'IoT Gateway Adapter',
        'Time Series Processor',
      ],
      trigger: 'Schedule: Every 5 minutes',
      approval: 'auto',
    },
    {
      id: 'grid-2',
      name: 'Anomaly Detector Agent',
      ref: '',
      role: 'contributor',
      goal: `Detect vibration, temperature, and voltage anomalies across all grid assets`,
      dependsOn: ['grid-1'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Monitoring MCP',
      tools: [
        'Vibration Analyzer',
        'Temperature Anomaly Detector',
        'Voltage Pattern Scanner',
        'Historical Comparator',
      ],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'grid-3',
      name: 'Failure Predictor Agent',
      ref: '',
      role: 'contributor',
      goal: `Predict equipment failures 2–4 weeks in advance using anomaly patterns and failure history`,
      dependsOn: ['grid-2'],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Predictive Analytics MCP',
      tools: [
        'Failure Correlation Engine',
        'Risk Scorer',
        'Maintenance Scheduler',
        'Work Order Generator',
      ],
      trigger: '',
      approval: 'manual',
    },
    {
      id: 'grid-4',
      name: 'Grid Balancer Agent',
      ref: '',
      role: 'finalizer',
      goal: `Optimise real-time load balancing across renewable and conventional generation sources`,
      dependsOn: ['grid-3'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Grid Control MCP',
      tools: [
        'Load Forecaster',
        'Renewable Integration Model',
        'Dispatch Optimiser',
        'Grid Stability Checker',
      ],
      trigger: '',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-grid-1',
      trigger: 'grid_instability_detected',
      action: 'emergency_rebalance',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'critical',
    },
    {
      id: 'rr-grid-2',
      trigger: 'forecast_deviation_high',
      action: 'recalibrate_model',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '10s',
    staleThreshold: '30s',
    unresponsiveThreshold: '60s',
    stuckThreshold: '120s',
    maxRestartAttempts: 5,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['json', 'csv', 'pdf'],
    template: 'Grid Operations Dashboard',
    storage: 's3://reports/grid-operations/',
  },
};

export const PROCESS_CITIZEN_REQUESTS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'process-citizen-requests',
  version: '0.0.1',
  name: 'Process Citizen Requests Team',
  description: `A multi-agent team that automates citizen request processing for government agencies. Classifies and triages permits, FOIA requests, and benefit claims from multiple channels. Models policy impacts across population datasets and ensures every automated decision is explainable, auditable, and compliant with transparency mandates.`,
  tags: [
    'government',
    'public-sector',
    'civic',
    'policy',
    'compliance',
    'transparency',
  ],
  enabled: true,
  icon: 'organization',
  emoji: '🏛️',
  color: '#0550ae',
  agentSpecId: 'process-citizen-requests:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Citizen Services Orchestrator Agent',
    ref: '',
    model: 'openai-gpt-4-1',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Route incoming citizen requests to the Intake Agent for classification and triage, then to the Case Processor for handling and routing, then to the Policy Analyst for impact assessment on relevant items, then to the Transparency Agent for audit trail and public documentation. Escalate urgent citizen safety issues immediately to supervisors.`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'cit-1',
      name: 'Intake & Classification Agent',
      ref: '',
      role: 'initiator',
      goal: `Classify, triage, and route citizen submissions from web portals, email, and documents`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Citizen Portal MCP',
      tools: [
        'Request Classifier',
        'Urgency Assessor',
        'Jurisdiction Router',
        'OCR Scanner',
      ],
      trigger: 'Event: new citizen request received',
      approval: 'auto',
    },
    {
      id: 'cit-2',
      name: 'Case Processor Agent',
      ref: '',
      role: 'contributor',
      goal: `Process and route requests to appropriate departments with required documentation`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Case Management MCP',
      tools: [
        'Case Creator',
        'Document Assembler',
        'Department Router',
        'Status Tracker',
      ],
      trigger: 'On completion of Intake Agent',
      approval: 'auto',
    },
    {
      id: 'cit-3',
      name: 'Policy Impact Analyst Agent',
      ref: '',
      role: 'contributor',
      goal: `Model policy outcomes across population datasets with scenario simulation`,
      dependsOn: ['cit-2'],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Policy Analytics MCP',
      tools: [
        'Monte Carlo Simulator',
        'Demographic Analyzer',
        'Budget Impact Model',
        'Scenario Comparator',
      ],
      trigger: '',
      approval: 'manual',
    },
    {
      id: 'cit-4',
      name: 'Transparency & Audit Agent',
      ref: '',
      role: 'finalizer',
      goal: `Generate explainable decision documentation with full audit trail for public record`,
      dependsOn: ['cit-3'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Compliance MCP',
      tools: [
        'Decision Explainer',
        'Audit Trail Builder',
        'FOIA Compliance Checker',
        'Public Record Generator',
      ],
      trigger: '',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-cit-1',
      trigger: 'priority_request_detected',
      action: 'fast_track_processing',
      auto: true,
      maxRetries: 2,
      escalateAfterRetries: 2,
      priority: 'high',
    },
    {
      id: 'rr-cit-2',
      trigger: 'policy_ambiguity_detected',
      action: 'request_human_review',
      auto: false,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'medium',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: false,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'json'],
    template: 'Citizen Request Processing Report',
    storage: 's3://reports/citizen-requests/',
  },
};

export const PROCESS_CLINICAL_TRIAL_DATA_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'process-clinical-trial-data',
  version: '0.0.1',
  name: 'Process Clinical Trial Data Team',
  description: `A multi-agent team that automates clinical trial data processing across dozens of trial sites. Harmonises patient records and lab results to CDISC SDTM format, detects safety signals and adverse events in real time, and prepares submission-ready datasets — all with strict HIPAA and GxP compliance guardrails.`,
  tags: [
    'healthcare',
    'pharma',
    'clinical-trials',
    'patient-data',
    'compliance',
  ],
  enabled: true,
  icon: 'heart',
  emoji: '🏥',
  color: '#cf222e',
  agentSpecId: 'process-clinical-trial-data:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'Clinical Data Orchestrator Agent',
    ref: '',
    model: 'anthropic-claude-sonnet-4',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Route incoming data through the Ingestion Agent first for format detection and parsing, then to Harmonisation Agent for CDISC SDTM standardisation, then Safety Monitor for adverse event screening, then Submission Preparer for final dataset assembly. Escalate serious adverse events (SAEs) immediately to the medical officer.`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '600s', retryOnFailure: true, maxRetries: 2 },
  agents: [
    {
      id: 'ct-1',
      name: 'Data Ingestion Agent',
      ref: '',
      role: 'initiator',
      goal: `Ingest patient records, lab results, and CRFs from clinical sites`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Clinical EDC MCP',
      tools: [
        'Medidata Connector',
        'Veeva Vault Reader',
        'Oracle Clinical Adapter',
        'Format Detector',
      ],
      trigger: 'Event: new data batch received from site',
      approval: 'auto',
    },
    {
      id: 'ct-2',
      name: 'Harmonisation Agent',
      ref: '',
      role: 'contributor',
      goal: `Standardise all data to CDISC SDTM format with MedDRA coding`,
      dependsOn: ['ct-1'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Data Standards MCP',
      tools: [
        'SDTM Mapper',
        'MedDRA Coder',
        'Unit Converter',
        'Site Normaliser',
      ],
      trigger: '',
      approval: 'auto',
    },
    {
      id: 'ct-3',
      name: 'Safety Monitor Agent',
      ref: '',
      role: 'contributor',
      goal: `Screen every data point for adverse events and safety signals`,
      dependsOn: ['ct-2'],
      subagents: [],
      model: 'anthropic-claude-sonnet-4',
      mcpServer: 'Safety Database MCP',
      tools: [
        'AE Classifier',
        'Signal Detector',
        'SAE Escalator',
        'Evidence Trail Builder',
      ],
      trigger: '',
      approval: 'manual',
    },
    {
      id: 'ct-4',
      name: 'Submission Preparer Agent',
      ref: '',
      role: 'finalizer',
      goal: `Assemble submission-ready SDTM datasets with validation and define.xml`,
      dependsOn: ['ct-3'],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Submission MCP',
      tools: [
        'Dataset Validator',
        'Define.xml Generator',
        'PDF Report Builder',
        'Compliance Checker',
      ],
      trigger: '',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-clin-1',
      trigger: 'safety_signal_detected',
      action: 'halt_and_escalate',
      auto: true,
      maxRetries: 0,
      escalateAfterRetries: 0,
      priority: 'critical',
    },
    {
      id: 'rr-clin-2',
      trigger: 'data_integrity_violation',
      action: 'quarantine_and_notify',
      auto: true,
      maxRetries: 1,
      escalateAfterRetries: 1,
      priority: 'critical',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '10s',
    staleThreshold: '45s',
    unresponsiveThreshold: '90s',
    stuckThreshold: '180s',
    maxRestartAttempts: 2,
  },
  notifications: {
    on_start: true,
    on_completion: true,
    on_failure: true,
    on_escalation: true,
  },
  output: {
    formats: ['pdf', 'json', 'xml'],
    template: 'Clinical Trial Data Report',
    storage: 's3://reports/clinical-trials/',
  },
};

export const SYNC_CRM_CONTACTS_TEAM_SPEC_0_0_1: TeamSpec = {
  id: 'sync-crm-contacts',
  version: '0.0.1',
  name: 'Sync CRM Contacts Team',
  description: `A multi-agent team that collects and aggregates contact data from multiple CRM sources, analyzes and deduplicates records, writes cleaned data back, and generates sync summary reports.`,
  tags: ['sales', 'crm', 'data-sync', 'deduplication'],
  enabled: true,
  icon: 'people',
  emoji: '🔄',
  color: '#0969da',
  agentSpecId: 'sync-crm-contacts:0.0.1',
  orchestrationProtocol: 'datalayer',
  executionMode: 'sequential',
  supervisor: {
    name: 'CRM Orchestrator Agent',
    ref: '',
    model: 'bedrock:us.anthropic.claude-sonnet-4-6',
    goal: ``,
    instructions: ``,
    approval: 'auto',
    canTerminate: true,
  },
  routingInstructions: `Route data collection tasks to the Data Collector first, then analysis, then sync, then reporting. Escalate to human if sync fails 3 times.`,
  delegation: {
    maxDepth: 2,
    allowPeerDelegation: false,
    includeGeneralPurpose: false,
  },
  context: { sharing: 'shared' },
  validation: { timeout: '300s', retryOnFailure: true, maxRetries: 3 },
  agents: [
    {
      id: 'tm-1',
      name: 'Data Collector Agent',
      ref: '',
      role: 'initiator',
      goal: `Collect and aggregate contact data from multiple CRM sources`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Data Processing MCP',
      tools: ['API Connector', 'Data Parser'],
      trigger: 'Schedule: Daily at 2:00 AM',
      approval: 'auto',
    },
    {
      id: 'tm-2',
      name: 'Analyzer Agent',
      ref: '',
      role: 'contributor',
      goal: `Analyze collected data and identify patterns and duplicates`,
      dependsOn: [],
      subagents: [],
      model: 'bedrock:us.anthropic.claude-sonnet-4-6',
      mcpServer: 'Analytics MCP',
      tools: ['Statistical Analysis', 'ML Predictor', 'Deduplicator'],
      trigger: 'On completion of Data Collector',
      approval: 'manual',
    },
    {
      id: 'tm-3',
      name: 'Sync Writer Agent',
      ref: '',
      role: 'contributor',
      goal: `Write cleaned and merged contacts back to the CRM systems`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'CRM Write MCP',
      tools: ['Salesforce Connector', 'HubSpot Connector'],
      trigger: 'On completion of Analyzer',
      approval: 'manual',
    },
    {
      id: 'tm-4',
      name: 'Report Generator Agent',
      ref: '',
      role: 'finalizer',
      goal: `Generate sync summary reports and send notifications`,
      dependsOn: [],
      subagents: [],
      model: 'openai-gpt-4-1',
      mcpServer: 'Document Generation MCP',
      tools: ['PDF Generator', 'Chart Builder', 'Email Sender'],
      trigger: 'On completion of Sync Writer',
      approval: 'auto',
    },
  ],
  reactionRules: [
    {
      id: 'rr-crm-1',
      trigger: 'sync_conflict_detected',
      action: 'log_and_skip',
      auto: true,
      maxRetries: 3,
      escalateAfterRetries: 3,
      priority: 'medium',
    },
    {
      id: 'rr-crm-2',
      trigger: 'api_rate_limit_hit',
      action: 'backoff_and_retry',
      auto: true,
      maxRetries: 5,
      escalateAfterRetries: 5,
      priority: 'low',
    },
  ],
  healthMonitoring: {
    heartbeatInterval: '30s',
    staleThreshold: '120s',
    unresponsiveThreshold: '300s',
    stuckThreshold: '600s',
    maxRestartAttempts: 3,
  },
  notifications: {
    on_start: false,
    on_completion: true,
    on_failure: true,
    on_escalation: false,
  },
  output: {
    formats: ['json', 'csv'],
    template: 'CRM Sync Summary',
    storage: 's3://reports/crm-sync/',
  },
};

// ============================================================================
// Team Specs Registry
// ============================================================================

export const TEAM_SPECS: Record<string, TeamSpec> = {
  'analyze-campaign-performance': ANALYZE_CAMPAIGN_PERFORMANCE_TEAM_SPEC_0_0_1,
  'analyze-support-tickets': ANALYZE_SUPPORT_TICKETS_TEAM_SPEC_0_0_1,
  'audit-inventory-levels': AUDIT_INVENTORY_LEVELS_TEAM_SPEC_0_0_1,
  'automate-regulatory-reporting':
    AUTOMATE_REGULATORY_REPORTING_TEAM_SPEC_0_0_1,
  'comprehensive-sales-analytics':
    COMPREHENSIVE_SALES_ANALYTICS_TEAM_SPEC_0_0_1,
  jupyter: JUPYTER_TEAM_SPEC_0_0_1,
  'optimize-grid-operations': OPTIMIZE_GRID_OPERATIONS_TEAM_SPEC_0_0_1,
  'process-citizen-requests': PROCESS_CITIZEN_REQUESTS_TEAM_SPEC_0_0_1,
  'process-clinical-trial-data': PROCESS_CLINICAL_TRIAL_DATA_TEAM_SPEC_0_0_1,
  'sync-crm-contacts': SYNC_CRM_CONTACTS_TEAM_SPEC_0_0_1,
};

function resolveTeamId(teamId: string): string {
  if (teamId in TEAM_SPECS) return teamId;
  const idx = teamId.lastIndexOf(':');
  if (idx > 0) {
    const base = teamId.slice(0, idx);
    if (base in TEAM_SPECS) return base;
  }
  return teamId;
}

/**
 * Get a team specification by ID.
 */
export function getTeamSpec(teamId: string): TeamSpec | undefined {
  return TEAM_SPECS[resolveTeamId(teamId)];
}

/**
 * List all available team specifications.
 *
 * @param prefix - If provided, only return specs whose ID starts with this prefix.
 */
export function listTeamSpecs(prefix?: string): TeamSpec[] {
  const specs = Object.values(TEAM_SPECS);
  return prefix !== undefined
    ? specs.filter(s => s.id.startsWith(prefix))
    : specs;
}
