# Copyright (c) 2025-2026 Datalayer, Inc.
# Distributed under the terms of the Modified BSD License.
"""
Op Catalog.

Orchestrated, supervised workflows: Cogs, and how their work is verified.
Every Op is resolved: its Guards, its Gates and its Track are in it.

This file is AUTO-GENERATED from YAML specifications.
DO NOT EDIT MANUALLY - run 'make specs' to regenerate.
"""

from typing import Dict

from agent_runtimes.types import OpSpec

# ============================================================================
# Op Definitions
# ============================================================================

OP_SALES_PIPELINE_BOARD_REPORT_0_0_1 = OpSpec.model_validate(
    {
        "id": "op-sales-pipeline-board-report",
        "version": "0.0.1",
        "name": "Sales Pipeline Board Report",
        "description": "Builds the sales pipeline report for the board: figures computed from the pipeline data by the definitions the sales organization uses, checked against their sources and by an independent path, reviewed by Finance, and approved by a person before they reach the board.",
        "owner": "Datalayer Finance <info@datalayer.io>",
        "goal": "Produce the board's sales pipeline report for the period — stage health, conversion, weighted forecast, regional performance and risks — with every figure traceable to the pipeline data.",
        "cogs": [
            {
                "id": "cog-sales-pipeline-board-report",
                "agent": "worker-sales-pipeline-board-report",
                "frames": ["sales-pipeline", "board-reporting"],
                "kind": "context",
            }
        ],
        "frames": ["datalayer"],
        "supervisor": {
            "model": "bedrock:us.anthropic.claude-sonnet-4-6",
            "instructions": "Run the Cog on the pipeline data of the period. Send a step back to the Cog when a Gate asks for a retry or a revision, with what the Guard found. Never release the report yourself: it leaves through the release approval Gate.",
        },
        "guards": {
            "preflight": [
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "required-frame-guard",
                    "version": "0.0.1",
                    "name": "Required Frame Guard",
                    "description": "Checks, before any work starts, that every Frame the Op and its Cogs declare exists, is enabled and has been applied to the Cogs' context.",
                    "category": "policy-safety",
                    "stages": ["preflight"],
                    "method": "algorithmic",
                    "check": "Every Frame named by the Op and by its Cogs resolves, is enabled, and appears in the context each Cog was given.",
                    "signals": [
                        {
                            "name": "frames_missing",
                            "type": "boolean",
                            "description": "A declared Frame is absent, disabled or was not applied.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["frames", "configuration"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "permission-guard",
                    "version": "0.0.1",
                    "name": "Permission Guard",
                    "description": "Checks that the person or the system launching the Op holds every permission the Op's Cogs need, as the guardrail states them.",
                    "category": "policy-safety",
                    "stages": ["preflight"],
                    "method": "algorithmic",
                    "check": "Each permission the Op's Cogs use is granted to the launching identity by the guardrail; nothing the guardrail denies is requested.",
                    "signals": [
                        {
                            "name": "permission_denied",
                            "type": "boolean",
                            "description": "A permission the Op needs is not granted.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["permissions", "identity"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "datalayer",
                    "identity_name": "dave@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": True,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": True,
                        "deploy_production": True,
                    },
                    "token_limits": {
                        "per_run": "200K",
                        "per_day": "5M",
                        "per_month": "50M",
                    },
                    "data_scope": {
                        "allowed_systems": ["postgresql", "mongodb", "s3", "kafka"],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": ["*SSN*", "*Bank*", "*IBAN*"],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 100000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": True,
                        "pii_action": "redact",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [
                            "Schema changes",
                            "Drop or truncate operations",
                            "Production data modifications",
                        ],
                        "auto_approved": [
                            "Read queries",
                            "Data transformations",
                            "Pipeline orchestration",
                        ],
                    },
                    "tool_limits": {
                        "max_tool_calls": 500,
                        "max_query_rows": 1000000,
                        "max_query_runtime": "300s",
                        "max_time_window_days": 365,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 90,
                        "require_lineage_in_report": True,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": True,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "data-source-authorization-guard",
                    "version": "0.0.1",
                    "name": "Data Source Authorization Guard",
                    "description": "Checks that each system, object and field the Op is about to read is inside the data scope of the guardrail, and that no denied field is requested.",
                    "category": "policy-safety",
                    "stages": ["preflight"],
                    "method": "algorithmic",
                    "check": "Every data source named by the run is among the guardrail's allowed systems and objects; none is a denied object or matches a denied field.",
                    "signals": [
                        {
                            "name": "unauthorized_source",
                            "type": "boolean",
                            "description": "A data source outside the allowed scope is requested.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["data", "authorization"],
                    "guardrail": "data-engineering-power-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
            ],
            "in_flight": [
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "tool-use-policy-guard",
                    "version": "0.0.1",
                    "name": "Tool Use Policy Guard",
                    "description": "Watches each tool call a Cog makes: the tool is one the Cog declares, and the calls stay within the guardrail's tool limits.",
                    "category": "policy-safety",
                    "stages": ["in_flight"],
                    "method": "algorithmic",
                    "check": "Every tool called is declared by the calling Cog; the number of calls, the rows queried and the query runtime stay within the guardrail's limits.",
                    "signals": [
                        {
                            "name": "tool_violation",
                            "type": "boolean",
                            "description": "An undeclared tool was called, or a tool limit was exceeded.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["tools", "limits"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "azure-ad",
                    "identity_name": "viewer-group@acme.onmicrosoft.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": False,
                        "access_internet": False,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "10K",
                        "per_day": "50K",
                        "per_month": "500K",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [
                            "*SSN*",
                            "*Bank*",
                            "*IBAN*",
                            "*Password*",
                            "*Secret*",
                        ],
                    },
                    "data_handling": {
                        "default_aggregation": True,
                        "allow_row_level_output": False,
                        "max_rows_in_output": 0,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": True,
                        "pii_action": "redact",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": ["Any operation beyond read"],
                        "auto_approved": ["Aggregated read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 10,
                        "max_query_rows": 10000,
                        "max_query_runtime": "15s",
                        "max_time_window_days": 30,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": True,
                        "retain_days": 90,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": True,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "sensitive-data-guard",
                    "version": "0.0.1",
                    "name": "Sensitive Data Guard",
                    "description": "Detects personal data, credentials and the guardrail's denied fields in what a Cog is about to send out, and in the final output.",
                    "category": "policy-safety",
                    "stages": ["in_flight", "post_run"],
                    "method": "algorithmic",
                    "check": "No output, tool argument or outbound message contains a credential, a field matching the guardrail's denied fields, or personal data the guardrail's handling rules require to be redacted.",
                    "signals": [
                        {
                            "name": "sensitive_data_detected",
                            "type": "boolean",
                            "description": "Sensitive data was found where it must not be.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["privacy", "pii", "secrets"],
                    "guardrail": "restricted-viewer",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "confidence-guard",
                    "version": "0.0.1",
                    "name": "Confidence Guard",
                    "description": "Collects the confidence each Cog reports on its result, and the lowest of them for the run, so that a Gate can route unsure work to a person.",
                    "category": "algorithmic",
                    "stages": ["in_flight", "post_run"],
                    "method": "algorithmic",
                    "check": "Each Cog result carries a confidence between 0 and 1; the Guard reports the lowest, and fails when a result carries none.",
                    "signals": [
                        {
                            "name": "confidence",
                            "type": "number",
                            "description": "The lowest confidence a Cog reported, between 0 and 1.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["confidence"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
            ],
            "post_run": [
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "schema-guard",
                    "version": "0.0.1",
                    "name": "Schema Guard",
                    "description": "Validates the structure of the output against the schema the Op's output declares: required sections, fields, types.",
                    "category": "algorithmic",
                    "stages": ["post_run"],
                    "method": "algorithmic",
                    "check": "The output validates against its declared schema: every required section and field is present and of the declared type.",
                    "signals": [
                        {
                            "name": "schema_valid",
                            "type": "boolean",
                            "description": "The output conforms to its schema.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["schema", "structure"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "source-grounding-guard",
                    "version": "0.0.1",
                    "name": "Source Grounding Guard",
                    "description": "Checks each claim and each figure of the output against the sources and the computations the run used: a figure traces to the code that produced it.",
                    "category": "source-grounding",
                    "stages": ["post_run"],
                    "method": "cog",
                    "check": "Every factual claim cites a source that supports it, and every figure equals the value computed in the sandbox from the authorized data.",
                    "signals": [
                        {
                            "name": "unsupported_claims",
                            "type": "number",
                            "description": "How many claims or figures have no supporting source or computation.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["sources", "evidence"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "consensus-guard",
                    "version": "0.0.1",
                    "name": "Consensus Guard",
                    "description": "Recomputes the key figures by an independent path — another Cog, or the same Cog on another model — and measures how far the two disagree.",
                    "category": "consensus",
                    "stages": ["post_run"],
                    "method": "cog",
                    "check": "The key figures of the output are recomputed independently; the Guard reports the share of them on which the two paths disagree.",
                    "signals": [
                        {
                            "name": "consensus_disagreement",
                            "type": "number",
                            "description": "The share of key figures on which independent paths disagree, between 0 and 1.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["consensus", "verification"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "azure-ad",
                    "identity_name": "viewer-group@acme.onmicrosoft.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": False,
                        "access_internet": False,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "10K",
                        "per_day": "50K",
                        "per_month": "500K",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [
                            "*SSN*",
                            "*Bank*",
                            "*IBAN*",
                            "*Password*",
                            "*Secret*",
                        ],
                    },
                    "data_handling": {
                        "default_aggregation": True,
                        "allow_row_level_output": False,
                        "max_rows_in_output": 0,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": True,
                        "pii_action": "redact",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": ["Any operation beyond read"],
                        "auto_approved": ["Aggregated read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 10,
                        "max_query_rows": 10000,
                        "max_query_runtime": "15s",
                        "max_time_window_days": 30,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": True,
                        "retain_days": 90,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": True,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "sensitive-data-guard",
                    "version": "0.0.1",
                    "name": "Sensitive Data Guard",
                    "description": "Detects personal data, credentials and the guardrail's denied fields in what a Cog is about to send out, and in the final output.",
                    "category": "policy-safety",
                    "stages": ["in_flight", "post_run"],
                    "method": "algorithmic",
                    "check": "No output, tool argument or outbound message contains a credential, a field matching the guardrail's denied fields, or personal data the guardrail's handling rules require to be redacted.",
                    "signals": [
                        {
                            "name": "sensitive_data_detected",
                            "type": "boolean",
                            "description": "Sensitive data was found where it must not be.",
                        }
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["privacy", "pii", "secrets"],
                    "guardrail": "restricted-viewer",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "expert-sampling-guard",
                    "version": "0.0.1",
                    "name": "Expert Sampling Guard",
                    "description": "Routes the output — every one of a high-risk Op, a sample of the others — to a named expert, and records what they decided.",
                    "category": "expert",
                    "stages": ["post_run"],
                    "method": "human",
                    "check": "An expert in the subject reads the output and its evidence, and approves it, edits it or sends it back.",
                    "signals": [
                        {
                            "name": "expert_approved",
                            "type": "boolean",
                            "description": "The expert approved the output.",
                        },
                        {
                            "name": "high_risk",
                            "type": "boolean",
                            "description": "The output is of a kind every instance of which is reviewed.",
                        },
                    ],
                    "required": True,
                    "enabled": True,
                    "tags": ["expert", "review"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
            ],
            "continuous": [
                {
                    "identity_provider": "datalayer",
                    "identity_name": "dave@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": True,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": True,
                        "deploy_production": True,
                    },
                    "token_limits": {
                        "per_run": "200K",
                        "per_day": "5M",
                        "per_month": "50M",
                    },
                    "data_scope": {
                        "allowed_systems": ["postgresql", "mongodb", "s3", "kafka"],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": ["*SSN*", "*Bank*", "*IBAN*"],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 100000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": True,
                        "pii_action": "redact",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [
                            "Schema changes",
                            "Drop or truncate operations",
                            "Production data modifications",
                        ],
                        "auto_approved": [
                            "Read queries",
                            "Data transformations",
                            "Pipeline orchestration",
                        ],
                    },
                    "tool_limits": {
                        "max_tool_calls": 500,
                        "max_query_rows": 1000000,
                        "max_query_runtime": "300s",
                        "max_time_window_days": 365,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 90,
                        "require_lineage_in_report": True,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": True,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "regression-guard",
                    "version": "0.0.1",
                    "name": "Regression Guard",
                    "description": "Replays a golden set of past runs after a model, a Frame, a Cog or the Op itself changes, and compares the results with the validated ones.",
                    "category": "regression-drift",
                    "stages": ["continuous"],
                    "method": "algorithmic",
                    "check": "On the golden set, the share of runs whose output departs from the validated one stays under the threshold the Op's owner set.",
                    "signals": [
                        {
                            "name": "regression_rate",
                            "type": "number",
                            "description": "The share of golden runs whose output changed, between 0 and 1.",
                        }
                    ],
                    "required": False,
                    "enabled": True,
                    "tags": ["regression", "drift"],
                    "guardrail": "data-engineering-power-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
                {
                    "identity_provider": "datalayer",
                    "identity_name": "alice@acme.com",
                    "permissions": {
                        "read_data": True,
                        "write_data": False,
                        "execute_code": True,
                        "access_internet": True,
                        "send_email": False,
                        "deploy_production": False,
                    },
                    "token_limits": {
                        "per_run": "50K",
                        "per_day": "500K",
                        "per_month": "5M",
                    },
                    "data_scope": {
                        "allowed_systems": [],
                        "allowed_objects": [],
                        "denied_objects": [],
                        "denied_fields": [],
                    },
                    "data_handling": {
                        "default_aggregation": False,
                        "allow_row_level_output": True,
                        "max_rows_in_output": 1000,
                        "redact_fields": [],
                        "hash_fields": [],
                        "pii_detection": False,
                        "pii_action": "warn",
                    },
                    "approval_policy": {
                        "require_manual_approval_for": [],
                        "auto_approved": ["All read-only queries"],
                    },
                    "tool_limits": {
                        "max_tool_calls": 50,
                        "max_query_rows": 100000,
                        "max_query_runtime": "60s",
                        "max_time_window_days": 90,
                    },
                    "audit": {
                        "log_tool_calls": True,
                        "log_query_metadata_only": False,
                        "retain_days": 30,
                        "require_lineage_in_report": False,
                    },
                    "content_safety": {
                        "treat_crm_text_fields_as_untrusted": False,
                        "do_not_follow_instructions_from_data": True,
                    },
                    "id": "outcome-guard",
                    "version": "0.0.1",
                    "name": "Outcome Guard",
                    "description": "Measures, over time, whether the Op's outputs are used as intended: accepted without rework, on time, with the decision they were made for taken.",
                    "category": "outcome",
                    "stages": ["continuous"],
                    "method": "human",
                    "check": "Over the review period, the share of outputs accepted without rework by the people they were produced for meets the Op's goal.",
                    "signals": [
                        {
                            "name": "outcome_met",
                            "type": "boolean",
                            "description": "The Op met its outcome goal over the review period.",
                        }
                    ],
                    "required": False,
                    "enabled": True,
                    "tags": ["outcome", "value"],
                    "guardrail": "default-platform-user",
                    "icon": "shield-check",
                    "emoji": "🛡️",
                },
            ],
        },
        "gates": [
            {
                "id": "configuration-check",
                "version": "0.0.1",
                "name": "Configuration Check",
                "description": "Stops an Op before it starts when a Frame it requires is missing, a permission is not granted or a data source is not authorized.",
                "stage": "preflight",
                "guards": [
                    "required-frame-guard:0.0.1",
                    "permission-guard:0.0.1",
                    "data-source-authorization-guard:0.0.1",
                ],
                "when": "frames_missing or permission_denied or unauthorized_source",
                "then": "stop_and_escalate",
                "otherwise": "proceed",
                "reviewers": ["op-owner"],
                "max_retries": 0,
                "enabled": True,
                "tags": ["preflight"],
                "icon": "git-branch",
                "emoji": "🚦",
                "signals": [
                    "frames_missing",
                    "permission_denied",
                    "unauthorized_source",
                ],
            },
            {
                "id": "sensitive-data-stop",
                "version": "0.0.1",
                "name": "Sensitive Data Stop",
                "description": "Stops the Op and tells the data protection officer when sensitive data is detected in what a Cog is about to send out, or in the output.",
                "stage": "in_flight",
                "guards": ["sensitive-data-guard:0.0.1"],
                "when": "sensitive_data_detected",
                "then": "stop_and_escalate",
                "otherwise": "proceed",
                "reviewers": ["data-protection-officer"],
                "max_retries": 0,
                "enabled": True,
                "tags": ["privacy"],
                "icon": "git-branch",
                "emoji": "🚦",
                "signals": ["sensitive_data_detected"],
            },
            {
                "id": "tool-violation-retry",
                "version": "0.0.1",
                "name": "Tool Violation Retry",
                "description": "Sends a step back to its Cog when it called a tool it does not declare or exceeded a tool limit; after the retries are used up the Op stops.",
                "stage": "in_flight",
                "guards": ["tool-use-policy-guard:0.0.1"],
                "when": "tool_violation",
                "then": "retry",
                "otherwise": "proceed",
                "reviewers": [],
                "max_retries": 2,
                "enabled": True,
                "tags": ["tools"],
                "icon": "git-branch",
                "emoji": "🚦",
                "signals": ["tool_violation"],
            },
            {
                "id": "low-confidence-review",
                "version": "0.0.1",
                "name": "Low Confidence Review",
                "description": "Routes the output to human review when the lowest confidence a Cog reported is under 0.80. Low confidence is not a failure: it is where the autonomy granted to the Op ends.",
                "stage": "post_run",
                "guards": ["confidence-guard:0.0.1"],
                "when": "confidence < 0.80",
                "then": "human_review_required",
                "otherwise": "proceed",
                "reviewers": ["op-owner"],
                "max_retries": 0,
                "enabled": True,
                "tags": ["confidence", "human-in-the-loop"],
                "icon": "git-branch",
                "emoji": "🚦",
                "signals": ["confidence"],
            },
            {
                "id": "unsupported-claims-revision",
                "version": "0.0.1",
                "name": "Unsupported Claims Revision",
                "description": "Pauses the Op and asks for a revision when the output is not valid against its schema or carries a claim or a figure its sources do not support.",
                "stage": "post_run",
                "guards": ["schema-guard:0.0.1", "source-grounding-guard:0.0.1"],
                "when": "schema_valid == false or unsupported_claims > 0",
                "then": "pause",
                "otherwise": "proceed",
                "reviewers": [],
                "max_retries": 0,
                "enabled": True,
                "tags": ["evidence"],
                "icon": "git-branch",
                "emoji": "🚦",
                "signals": ["schema_valid", "unsupported_claims"],
            },
            {
                "id": "consensus-disagreement-review",
                "version": "0.0.1",
                "name": "Consensus Disagreement Review",
                "description": "Escalates to an expert when independent recomputations disagree on more than a quarter of the key figures.",
                "stage": "post_run",
                "guards": ["consensus-guard:0.0.1"],
                "when": "consensus_disagreement > 0.25",
                "then": "expert_review_required",
                "otherwise": "proceed",
                "reviewers": ["subject-matter-expert"],
                "max_retries": 0,
                "enabled": True,
                "tags": ["consensus"],
                "icon": "git-branch",
                "emoji": "🚦",
                "signals": ["consensus_disagreement"],
            },
            {
                "id": "release-approval",
                "version": "0.0.1",
                "name": "Release Approval",
                "description": "Requires a person to approve the output before it is released to its audience, whatever the Guards found. The expert's review is recorded beside the approval.",
                "stage": "post_run",
                "guards": ["expert-sampling-guard:0.0.1"],
                "when": "always",
                "then": "human_approval_required",
                "otherwise": "stop",
                "reviewers": ["op-owner", "finance"],
                "max_retries": 0,
                "enabled": True,
                "tags": ["approval", "human-in-the-loop"],
                "icon": "git-branch",
                "emoji": "🚦",
                "signals": [],
            },
            {
                "id": "quality-drift-review",
                "version": "0.0.1",
                "name": "Quality Drift Review",
                "description": "Puts the Op before an expert when more than one golden run in ten changed after an update, or when the Op missed its outcome goal over the review period.",
                "stage": "continuous",
                "guards": ["regression-guard:0.0.1", "outcome-guard:0.0.1"],
                "when": "regression_rate > 0.10 or outcome_met == false",
                "then": "expert_review_required",
                "otherwise": "proceed",
                "reviewers": ["op-owner", "subject-matter-expert"],
                "max_retries": 0,
                "enabled": True,
                "tags": ["drift", "outcome"],
                "icon": "git-branch",
                "emoji": "🚦",
                "signals": ["regression_rate", "outcome_met"],
            },
        ],
        "track": {
            "id": "financial-reporting",
            "version": "0.0.1",
            "name": "Financial Reporting Track",
            "description": "The complete record of an Op that produces financial reporting: every input and source, every model and setting, every Guard result, Gate decision, approval and edit. Kept seven years, readable by Finance and by audit, and fed back to Organizational Memory.",
            "retain_for": "7_years",
            "include": [
                "op",
                "frames_used",
                "cogs_invoked",
                "input_data",
                "source_documents",
                "model_versions",
                "configuration",
                "guard_results",
                "gate_decisions",
                "human_approvals",
                "human_edits",
                "final_output",
                "actions_taken",
                "timestamps",
                "user_identity",
                "permissions",
                "environment",
                "memory_links",
            ],
            "readers": ["finance", "internal-audit"],
            "redact": ["*Password*", "*Secret*", "*Token*", "*IBAN*"],
            "feeds_memory": True,
            "exchangeable": False,
            "enabled": True,
            "tags": ["finance", "audit"],
            "icon": "log",
            "emoji": "🧾",
            "retention_days": 2555,
        },
        "triggers": ["launcher", "command", "schedule"],
        "enabled": False,
        "tags": ["sales", "board", "reporting"],
        "icon": "workflow",
        "emoji": "📊",
        "color": "#1F883D",
        "lineage": ["datalayer", "sales-pipeline", "board-reporting"],
        "frame_guards": [
            {
                "id": "no-secrets",
                "category": "policy-safety",
                "description": "The output contains no credential, token, API key or password.",
                "required": True,
            },
            {
                "id": "totals-reconcile",
                "category": "algorithmic",
                "description": "The totals by stage, by region and by segment each add up to the total pipeline.",
                "required": True,
            },
            {
                "id": "definitions-applied",
                "category": "policy-safety",
                "description": "Conversion, weighted pipeline and coverage are computed as this Frame defines them.",
                "required": True,
            },
            {
                "id": "data-quality-reported",
                "category": "algorithmic",
                "description": "Rows excluded from a figure, and why, are counted and reported.",
                "required": True,
            },
            {
                "id": "summary-first",
                "category": "algorithmic",
                "description": "The report opens with a summary of at most one page, with the key figures, the risks and the asks.",
                "required": True,
            },
            {
                "id": "forecast-labelled",
                "category": "policy-safety",
                "description": "Every forward-looking figure is labelled as a forecast and carries its assumption.",
                "required": True,
            },
            {
                "id": "finance-review",
                "category": "expert",
                "description": "A person from Finance reviews the figures before the report is sent to the board.",
                "required": True,
            },
        ],
    }
)


# ============================================================================
# Op Catalog
# ============================================================================

OP_CATALOGUE: Dict[str, OpSpec] = {
    "op-sales-pipeline-board-report": OP_SALES_PIPELINE_BOARD_REPORT_0_0_1,
}


def get_op(op_id: str) -> OpSpec | None:
    """An Op, by `id` or `id:version`, or None."""
    found = OP_CATALOGUE.get(op_id)
    if found is not None:
        return found
    base, _, version = op_id.rpartition(":")
    return OP_CATALOGUE.get(base) if base and "." in version else None


def list_ops() -> list[OpSpec]:
    """Every Op of the catalogue, resolved."""
    return list(OP_CATALOGUE.values())
