/*
 * Copyright (c) 2025-2026 Datalayer, Inc.
 * Distributed under the terms of the Modified BSD License.
 */

import { IContent } from './Content';
import { IItem } from './Item';
import type { Environment as EnvironmentDocument } from './environments.generated';
import type { IRuntimeEnvironment } from './Runtime';
import type { CreateRuntimeResponse } from './RuntimeDTO';

/**
 * The Environment specification, `environments.datalayer.io/v1alpha1`,
 * generated from the JSON Schema `code-sandboxes` exports from its pydantic
 * models (PLAN_ENV.md, D-14). Regenerated by `npm run generate:environments`.
 */
export * as EnvironmentSchema from './environments.generated';

/** An Environment document: `apiVersion`, `kind`, `metadata` and `spec`. */
export type { EnvironmentDocument };

export type IEnvironment = IItem & {
  type: 'environment';
};

export interface IResources {
  cpu: string;
  memory: string;
  'nvidia.com/gpu'?: string;
}

/**
 * Code snippet
 */
export interface ISnippet {
  /**
   * Snippet summary
   */
  title: string;
  /**
   * Snippet long description
   */
  description?: string;
  /**
   * Code snippet
   */
  code: string;
}

/** Where an environment comes from: the platform's catalogue, or a user's registry. */
export type EnvironmentOrigin = 'platform' | 'user';

/** Whose a user environment is: a person's account, or an organization's. */
export type EnvironmentOwnerType = 'user' | 'organization';

/**
 * Who a user environment is shown to (D-19). An environment becomes `public`
 * only by publishing a version to the Library (D-12).
 */
export type EnvironmentVisibility = 'private' | 'organization' | 'public';

/**
 * Where a version stands (section 4.2), as `VersionState` of
 * `code_sandboxes.environments.lifecycle` names it.
 */
export type EnvironmentVersionStatus =
  | 'draft'
  | 'resolving'
  | 'resolved'
  | 'building'
  | 'validating'
  | 'ready'
  | 'partially_ready'
  | 'failed'
  | 'deprecated';

/** The build statuses nothing more happens to. Any other status is still to run or running. */
export const TERMINAL_ENVIRONMENT_BUILD_STATUSES = [
  'succeeded',
  'failed',
  'cancelled',
] as const;

/** The version a user environment's launches resolve to, as `GET /environments` names it. */
export interface IPromotedEnvironmentVersion {
  uid: string;
  version: number;
  status: EnvironmentVersionStatus;
}

/**
 * Datalayer environment
 */
export interface IDatalayerEnvironment {
  /**
   * Name
   */
  name: string;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Icon key (e.g. ai-agent -> AiAgentIcon)
   */
  icon?: string;
  /**
   * Execution language
   */
  language: string;
  /**
   * Docker image
   */
  dockerImage: string;
  /**
   * Example notebook URL
   */
  example?: string;
  /**
   * Example code snippets
   */
  snippets?: ISnippet[];
  /**
   * Associate kernel attributes
   */
  runtime?: {
    /**
     * Proposed display name
     */
    givenNameTemplate?: string;
  };

  /**
   * Environment credits burning rate
   */
  burning_rate: number;

  /**
   * Environment server resources
   */
  resources?: IResources;

  /**
   * The contents the Environment selects, as `{uid, name, mount, permissions}`.
   *
   * Absent when the Environment selects none.
   */
  contents?: IContent[];

  /**
   * The registry uid of a user environment. Absent on a platform entry.
   */
  uid?: string;

  /**
   * `user` for an environment of the registry. Absent on a platform entry.
   */
  origin?: EnvironmentOrigin;

  /**
   * A user environment's owner uid, or a platform entry's owner, such as
   * `datalayer` or the provider of an external catalogue entry.
   */
  owner?: string;

  /**
   * The version launches of a user environment resolve to, `null` while none
   * is promoted. Absent on a platform entry.
   */
  promotedVersion?: IPromotedEnvironmentVersion | null;

  /**
   * The variants the promoted version builds for, empty while none is
   * promoted. Absent on a platform entry.
   */
  variants?: string[];
}

// -- The registry (PLAN_ENV.md, section 9) -------------------------------------

/**
 * A refusal, as every registry route answers one (section 10): a code, a
 * message and the correlation id; the field at fault, the detail, and for a
 * code of the taxonomy whether a retry can succeed and what the user does.
 */
export interface IEnvironmentsError {
  code: string;
  message: string;
  correlationId: string;
  field?: string;
  detail?: Record<string, unknown>;
  retryable?: boolean;
  userAction?: string;
}

/** A user environment, as the registry answers it. */
export interface IEnvironmentRecord {
  uid: string;
  /** Unique per owner: a DNS-1123 label. */
  name: string;
  title: string;
  description: string;
  origin: EnvironmentOrigin;
  ownerType: EnvironmentOwnerType;
  ownerUid: string;
  visibility: EnvironmentVisibility;
  promotedVersionUid: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: string | null;
  deletedAt: string | null;
  /** What a conditional write names in `If-Match`. */
  etag: string;
}

/** A version of an environment: its specification, and where it stands. */
export interface IEnvironmentVersionRecord {
  uid: string;
  environmentUid: string;
  ownerUid: string;
  /** Monotonic per environment, from 1. */
  version: number;
  label: string;
  /** The specification, with its defaults written out. */
  spec: EnvironmentDocument;
  specSchemaVersion: string;
  /** `sha256:<hex>` of the canonical spec. */
  specDigest: string;
  contractVersion: string;
  sourceType: string;
  sourceFormat: string;
  sourceArchiveRef: string;
  sourceArchiveDigest: string;
  /** Empty until the version is resolved. */
  lockDigest: string;
  /** Variant to base digest, once resolved. */
  resolvedBases: Record<string, string>;
  status: EnvironmentVersionStatus;
  requiredVariants: string[];
  optionalVariants: string[];
  validationSummary: Record<string, unknown>;
  failureCode: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  promotedAt: string | null;
  deprecatedAt: string | null;
  /**
   * The promotion that last made this version the promoted one, kept after a
   * later one is promoted; `null` for a version never promoted, and absent
   * from a Runtimes before E1-15.
   */
  promotion?: IEnvironmentPromotionRecord | null;
  /** What a conditional write names in `If-Match`. */
  etag: string;
}

/** One artifact a promotion put in service, with the policy decision it carried (E1-08). */
export interface IEnvironmentPromotionPolicyDecision {
  artifactUid: string;
  variant: string;
  region: string;
  immutableReference: string;
  /** The artifact's scan summary, as E1-08 decides it; `null` when no decision was made. */
  policyDecision: Record<string, unknown> | null;
}

/** The promotion that last made a version its environment's promoted one (E1-15, D-11). */
export interface IEnvironmentPromotionRecord {
  promotedAt: string;
  /** The uid of who promoted it. */
  promotedBy: string;
  /** The version's optional variants with no artifact a sandbox starts from; empty for a ready version. */
  unavailableVariants: string[];
  /** What the promotion acknowledged: exactly `unavailableVariants`. */
  acknowledgedUnavailableVariants: string[];
  /** Whether any artifact carried a policy decision; false until E1-08 makes them. */
  policyDecisionMade: boolean;
  policyDecisions: IEnvironmentPromotionPolicyDecision[];
}

/** A runtime still running one of an environment's artifacts, as a refused deletion names it (E1-15). */
export interface IEnvironmentLiveRuntime {
  runtimeUid: string;
  versionUid: string;
  /** The digest of the artifact it runs. */
  digest: string;
}

/**
 * The `detail` of a refused deletion, 409 `DL_ENV_CONFLICT`: what still refers
 * to the environment, checked in this order.
 */
export interface IEnvironmentDeletionConflict {
  /** A version is promoted: promote none first. */
  promotedVersionUid?: string;
  /** How many of its artifacts are referenced. */
  referencedArtifacts?: number;
  /** The runtimes still running one of its artifacts, whoever launched them. */
  runtimes?: IEnvironmentLiveRuntime[];
}

/** The `detail` of a refused promotion, 409 `DL_ENV_CONFLICT`. */
export interface IEnvironmentPromotionConflict {
  status: EnvironmentVersionStatus;
  /** A partially ready version's: what the acknowledgement must name, exactly. */
  unavailableVariants?: string[];
  /** What the refused acknowledgement named. */
  acknowledgedUnavailableVariants?: string[];
}

/** The artifact a runtime was started from, as its answer names it (section 7.6, E1-11). */
export interface ILaunchedEnvironmentArtifact {
  uid: string;
  variant: string;
  region: string;
  /** What the sandbox started from: an OCI reference pinned by its digest. */
  immutable_reference: string;
  digest: string;
  contract_version: string;
  size_class: string;
}

/**
 * A runtime's user environment, as its answer names it (E1-11): beside the
 * name and title every runtime's environment carries, the version launched and
 * its artifact. Snake_case, as the rest of the runtime.
 */
export interface ILaunchedEnvironment extends IRuntimeEnvironment {
  uid: string;
  version_uid: string;
  version: number;
  contract_version: string;
  artifact: ILaunchedEnvironmentArtifact;
}

/**
 * What trying a version answers (E1-14): `POST /runtimes`' answer, its
 * runtime's environment naming the version tried and the artifact it started
 * from. `success` is false, and the runtime carries a `reason`, when the
 * Operator started none.
 */
export interface IEnvironmentTrial extends CreateRuntimeResponse {
  runtime: CreateRuntimeResponse['runtime'] & {
    environment: ILaunchedEnvironment;
  };
}

/** One build of one version, on one variant and region. */
export interface IEnvironmentBuildRecord {
  uid: string;
  environmentUid: string;
  versionUid: string;
  ownerUid: string;
  variant: string;
  region: string;
  /** Counted from 1; a retry is the next attempt. */
  attempt: number;
  /** The request's key, suffixed with the variant and region. */
  idempotencyKey: string;
  /** `queued` when created; see `TERMINAL_ENVIRONMENT_BUILD_STATUSES`. */
  status: string;
  errorCode: string;
  errorDetail: string;
  cacheHit: boolean;
  correlationId: string;
  requestedBy: string;
  cancelledBy: string;
  createdAt: string;
  startedAt: string | null;
  finishedAt: string | null;
  updatedAt: string;
  /** What a conditional write names in `If-Match`. */
  etag: string;
}

/** The artifact of one version, on one variant and region. */
export interface IEnvironmentArtifactRecord {
  uid: string;
  environmentUid: string;
  versionUid: string;
  ownerUid: string;
  variant: string;
  region: string;
  specDigest: string;
  lockDigest: string;
  baseDigest: string;
  providerAccount: string;
  providerNamespace: string;
  providerArtifactId: string;
  /** What a launch uses: an OCI digest, a template build, a snapshot id, an image id. */
  immutableReference: string;
  /** For operators; never launched. */
  mutableAlias: string;
  status: string;
  architecture: string;
  contractVersion: string;
  runtimeMetadata: Record<string, unknown>;
  sizeBytes: number;
  sbomRef: string;
  scanSummary: Record<string, unknown>;
  provenanceRef: string;
  signatureRef: string;
  referenceCount: number;
  lastUsedAt: string | null;
  retentionState: string;
  providerVerifiedAt: string | null;
  buildStartedAt: string | null;
  buildFinishedAt: string | null;
  createdAt: string;
  updatedAt: string;
  /** What a conditional write names in `If-Match`. */
  etag: string;
}

/** One chunk of a build's log, redacted before it was written (D-15). */
export interface IEnvironmentBuildLogChunk {
  /** Dense from 0. */
  sequence: number;
  text: string;
  /** In bytes. */
  size: number;
  createdAt: string;
}

/** One problem a variant has with a specification. */
export interface IEnvironmentCapabilityFinding {
  code: string;
  message: string;
  field?: string;
}

/** Whether one variant can build a specification, and why not. */
export interface IEnvironmentCapabilityReport {
  variant: string;
  supported: boolean;
  findings: IEnvironmentCapabilityFinding[];
}

/** What validating a version answers: a capability report per variant. */
export interface IEnvironmentValidationReport {
  versionUid: string;
  specDigest: string;
  supported: boolean;
  reports: IEnvironmentCapabilityReport[];
}

/** The filters and cursor of `GET /environments`. */
export interface IListEnvironmentsQuery {
  /** Only one owner's: an account uid, or a platform entry's owner such as `datalayer`. */
  owner?: string;
  /** Only the platform's, or only user environments. */
  origin?: EnvironmentOrigin;
  /** Only the environments offered on this variant. */
  variant?: string;
  /** Only the environments whose name or title holds this. */
  q?: string;
  /** The previous page's `nextCursor`. */
  cursor?: string;
  /** How many user environments a page holds, 1 to 200. */
  limit?: number;
}

/** The cursor and size of a page of a registry listing. */
export interface IEnvironmentsPageQuery {
  /** The previous page's `nextCursor`. */
  cursor?: string;
  /** How many items a page holds, 1 to 200. */
  limit?: number;
}

/** `POST /environments`. */
export interface ICreateEnvironmentRequest {
  name: string;
  title?: string;
  description?: string;
  visibility?: EnvironmentVisibility;
  /** `user` by default. */
  ownerType?: EnvironmentOwnerType;
  /** The caller's own uid by default; an organization's uid for its environment. */
  ownerUid?: string;
}

/** `PATCH /environments/{uid}`. */
export interface IUpdateEnvironmentRequest {
  title?: string;
  description?: string;
  visibility?: EnvironmentVisibility;
}

/** `PUT /environments/{uid}/promoted-version`. */
export interface IPromoteEnvironmentVersionRequest {
  /** The version to promote, or `null` to promote none. */
  versionUid: string | null;
  /** The unavailable variants of a partially ready version. */
  acknowledgeUnavailableVariants?: string[];
}

/** `POST /environment-versions/{uid}/trial`. */
export interface ITrialEnvironmentVersionRequest {
  /**
   * The most credits the trial spends. The service keeps a lower limit, and
   * lowers a higher one to its cap, `DATALAYER_RUNTIMES_TRIAL_CREDITS_LIMIT`
   * (5 by default), which is also the limit when none is given.
   */
  creditsLimit?: number;
}

/** `POST /environments/{uid}/versions`. */
export interface ICreateEnvironmentVersionRequest {
  spec: EnvironmentDocument;
  label?: string;
}

/** `PATCH /environment-versions/{uid}`. */
export interface IUpdateEnvironmentVersionRequest {
  spec?: EnvironmentDocument;
  label?: string;
}

/** `POST /environment-versions/{uid}/validate`. */
export interface IValidateEnvironmentVersionRequest {
  /** The version's own variants when absent. */
  variants?: string[];
}

/** `POST /environment-versions/{uid}/builds`. */
export interface ICreateEnvironmentBuildsRequest {
  /** The version's own variants when absent. */
  variants?: string[];
  /** A subset of `variants`. */
  requiredVariants?: string[];
  /** The spec's regions when absent, else `r1`. */
  regions?: string[];
  force?: boolean;
}

/** A page of an environment's versions. */
export interface IEnvironmentVersionsPage {
  versions: IEnvironmentVersionRecord[];
  nextCursor: string | null;
}

/** The builds one request queued. */
export interface IEnvironmentBuildsCreated {
  builds: IEnvironmentBuildRecord[];
}

/** A page of a version's builds. */
export interface IEnvironmentBuildsPage {
  builds: IEnvironmentBuildRecord[];
  nextCursor: string | null;
}

/** A page of a version's artifacts. */
export interface IEnvironmentArtifactsPage {
  artifacts: IEnvironmentArtifactRecord[];
  nextCursor: string | null;
}

/** A build's log chunks after a cursor. */
export interface IEnvironmentBuildLogPage {
  chunks: IEnvironmentBuildLogChunk[];
  /** The sequence of the last chunk read, or the cursor given when nothing new was written. */
  nextCursor: string | null;
  /** The build has ended and every chunk has been read. */
  complete: boolean;
}

export default IEnvironment;
