/*
 * Copyright (c) 2025-2026 Datalayer, Inc.
 * Distributed under the terms of the Modified BSD License.
 */

/**
 * Writes src/components/teams/jupyterThemeVariables.ts: JupyterLab's light
 * and dark theme variables (`--jp-*`), read from the theme extensions'
 * variables.css, so a notebook preview can carry its own mode on its own
 * subtree — JupyterLab writes them for the whole page.
 *
 *   node scripts/codegen/generate_jupyter_theme_variables.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

function variables(pkg) {
  const css = readFileSync(require.resolve(`${pkg}/style/variables.css`), 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '');
  const out = {};
  for (const block of css.matchAll(/:root\s*\{([\s\S]*?)\}/g)) {
    for (const declaration of block[1].split(';')) {
      const match = /^\s*(--jp-[\w-]+)\s*:\s*([\s\S]+?)\s*$/.exec(declaration);
      if (match) {
        out[match[1]] = match[2].replace(/\s+/g, ' ');
      }
    }
  }
  return out;
}

const light = variables('@jupyterlab/theme-light-extension');
const dark = variables('@jupyterlab/theme-dark-extension');
const target = new URL('../../src/components/teams/jupyterThemeVariables.ts', import.meta.url);
writeFileSync(
  target,
  `/*
 * Copyright (c) 2025-2026 Datalayer, Inc.
 * Distributed under the terms of the Modified BSD License.
 */

/**
 * JupyterLab's theme variables, light and dark, as its theme extensions state
 * them. Generated by scripts/codegen/generate_jupyter_theme_variables.mjs: do
 * not edit.
 *
 * @module components/teams/jupyterThemeVariables
 */

export const JUPYTER_LIGHT_VARIABLES: Readonly<Record<string, string>> = ${JSON.stringify(light, null, 2)};

export const JUPYTER_DARK_VARIABLES: Readonly<Record<string, string>> = ${JSON.stringify(dark, null, 2)};
`,
);
console.log(`light ${Object.keys(light).length}, dark ${Object.keys(dark).length}`);
